export { default as QuizPage } from './pages/QuizPage'
export { default as QuizHistory } from './pages/QuizHistory'
export { default as ResultPage } from './pages/ResultPage'
export { default as GradesPage } from './pages/GradesPage'
export { useQuiz } from './hooks/useQuiz'
export { useQuizAttempts } from './hooks/useQuizAttempts'
export { quizRoutes } from './routes'
